# Generated by Django 5.2.17 on 2026-09-14 10:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('business_audit', '0001_initial'),
        ('organization', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='auditentry',
            name='actor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='business_audit_entries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='auditentry',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='audit_entries', to='organization.company'),
        ),
        migrations.AddIndex(
            model_name='auditentry',
            index=models.Index(fields=['company', 'occurred_at'], name='business_au_company_e21dc8_idx'),
        ),
        migrations.AddIndex(
            model_name='auditentry',
            index=models.Index(fields=['object_type', 'object_id'], name='business_au_object__9292e8_idx'),
        ),
    ]
