# Generated by Django 5.2.17 on 2026-09-13 12:32

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organization', '0001_initial'),
        ('reference', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('party_type', models.CharField(choices=[('person', 'Person'), ('organization', 'Organization')], max_length=16)),
                ('display_name', models.CharField(max_length=200)),
                ('legal_name', models.CharField(blank=True, max_length=200)),
                ('is_customer', models.BooleanField(default=False)),
                ('is_supplier', models.BooleanField(default=False)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='parties', to='organization.company')),
            ],
            options={
                'verbose_name_plural': 'parties',
                'ordering': ['display_name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ContactMethod',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('kind', models.CharField(choices=[('email', 'Email'), ('phone', 'Phone')], max_length=12)),
                ('label', models.CharField(blank=True, max_length=60)),
                ('value', models.CharField(max_length=254)),
                ('is_primary', models.BooleanField(default=False)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='party_contacts', to='organization.company')),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_methods', to='party.party')),
            ],
            options={
                'ordering': ['party', 'kind', 'value'],
            },
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('label', models.CharField(blank=True, max_length=60)),
                ('line_1', models.CharField(max_length=200)),
                ('line_2', models.CharField(blank=True, max_length=200)),
                ('city', models.CharField(max_length=120)),
                ('region', models.CharField(blank=True, max_length=120)),
                ('postal_code', models.CharField(blank=True, max_length=32)),
                ('is_billing', models.BooleanField(default=False)),
                ('is_shipping', models.BooleanField(default=False)),
                ('is_default', models.BooleanField(default=False)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='party_addresses', to='organization.company')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='party_addresses', to='reference.country')),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='party.party')),
            ],
            options={
                'ordering': ['party', '-is_default', 'label', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='party',
            index=models.Index(fields=['company', 'party_type', 'is_active'], name='party_party_company_0d6afb_idx'),
        ),
        migrations.AddConstraint(
            model_name='contactmethod',
            constraint=models.UniqueConstraint(fields=('party', 'kind', 'value'), name='unique_party_contact_method'),
        ),
        migrations.AddConstraint(
            model_name='contactmethod',
            constraint=models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('party', 'kind'), name='one_primary_contact_per_kind'),
        ),
        migrations.AddConstraint(
            model_name='address',
            constraint=models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('party',), name='one_default_address_per_party'),
        ),
    ]
