# Generated by Django 5.2.17 on 2026-09-13 20:22

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0002_register_manifest'),
        ('organization', '0001_initial'),
        ('reference', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(max_length=40)),
                ('movement_type', models.CharField(choices=[('receipt', 'Receipt'), ('issue', 'Issue'), ('transfer', 'Transfer')], max_length=12)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('posted', 'Posted')], default='draft', max_length=12)),
                ('effective_at', models.DateTimeField()),
                ('reference', models.CharField(blank=True, max_length=160)),
                ('notes', models.TextField(blank=True)),
                ('idempotency_key', models.CharField(blank=True, max_length=120, null=True)),
                ('source_module', models.CharField(blank=True, max_length=64, null=True)),
                ('source_type', models.CharField(blank=True, max_length=64, null=True)),
                ('source_id', models.UUIDField(blank=True, null=True)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_movements', to='organization.company')),
            ],
            options={
                'ordering': ['-effective_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StockMovementLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sku_snapshot', models.CharField(max_length=64)),
                ('product_name_snapshot', models.CharField(max_length=200)),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=18)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_movement_lines', to='organization.company')),
                ('destination_warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stock_lines_in', to='organization.warehouse')),
                ('movement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='inventory.stockmovement')),
                ('product_variant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_movement_lines', to='catalog.productvariant')),
                ('source_warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stock_lines_out', to='organization.warehouse')),
                ('uom', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_movement_lines', to='reference.unitofmeasure')),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['company', 'status', 'effective_at'], name='inventory_s_company_13bfa6_idx'),
        ),
        migrations.AddConstraint(
            model_name='stockmovement',
            constraint=models.UniqueConstraint(fields=('company', 'number'), name='unique_stock_movement_number_per_company'),
        ),
        migrations.AddConstraint(
            model_name='stockmovement',
            constraint=models.UniqueConstraint(fields=('company', 'idempotency_key'), name='unique_stock_movement_idempotency_per_company'),
        ),
        migrations.AddConstraint(
            model_name='stockmovement',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('source_id__isnull', True), ('source_module__isnull', True), ('source_type__isnull', True)), models.Q(('source_id__isnull', False), ('source_module__isnull', False), ('source_type__isnull', False)), _connector='OR'), name='stock_movement_source_all_or_none'),
        ),
        migrations.AddIndex(
            model_name='stockmovementline',
            index=models.Index(fields=['company', 'product_variant'], name='inventory_s_company_db5988_idx'),
        ),
        migrations.AddConstraint(
            model_name='stockmovementline',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='stock_line_quantity_positive'),
        ),
        migrations.AddConstraint(
            model_name='stockmovementline',
            constraint=models.CheckConstraint(condition=models.Q(('source_warehouse__isnull', True), ('destination_warehouse__isnull', True), models.Q(('source_warehouse', models.F('destination_warehouse')), _negated=True), _connector='OR'), name='stock_line_distinct_warehouses'),
        ),
    ]
