# Generated by Django 5.2.17 on 2026-10-07 18:23

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organization', '0001_initial'),
        ('party', '0002_register_manifest'),
        ('reference', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=32)),
                ('name', models.CharField(max_length=160)),
                ('is_active', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='organization.company')),
            ],
            options={
                'ordering': ['code', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(max_length=40)),
                ('payer_display_name_snapshot', models.CharField(max_length=200)),
                ('payer_legal_name_snapshot', models.CharField(blank=True, max_length=200)),
                ('payment_date', models.DateField()),
                ('currency_code_snapshot', models.CharField(max_length=3)),
                ('currency_decimal_places_snapshot', models.PositiveSmallIntegerField()),
                ('amount', models.DecimalField(decimal_places=8, max_digits=38)),
                ('payment_method_code_snapshot', models.CharField(max_length=32)),
                ('payment_method_name_snapshot', models.CharField(max_length=160)),
                ('external_reference', models.CharField(blank=True, max_length=128)),
                ('idempotency_key', models.CharField(blank=True, max_length=128, null=True)),
                ('notes', models.TextField(blank=True)),
                ('recorded_at', models.DateTimeField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='organization.company')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reference.currency')),
                ('payer_party', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='party.party')),
                ('payment_method', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='payments.paymentmethod')),
            ],
            options={
                'ordering': ['-payment_date', '-recorded_at', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='paymentmethod',
            constraint=models.UniqueConstraint(fields=('company', 'code'), name='payments_method_code_uniq'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['company', 'payment_date'], name='payments_pa_company_0220e9_idx'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.UniqueConstraint(fields=('company', 'number'), name='payments_company_number_uniq'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.UniqueConstraint(condition=models.Q(('idempotency_key__isnull', False)), fields=('company', 'idempotency_key'), name='payments_company_key_uniq'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='payments_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.CheckConstraint(condition=models.Q(('amount__lt', Decimal('1E+30'))), name='payments_amount_range'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.CheckConstraint(condition=models.Q(('currency_decimal_places_snapshot__gte', 0), ('currency_decimal_places_snapshot__lte', 8)), name='payments_currency_precision'),
        ),
    ]
