# Generated by Django 5.2.17 on 2026-09-14 10:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('access', '0001_initial'),
        ('organization', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userbranchaccess',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branch_accesses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='usercompanyaccess',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_accesses', to='organization.company'),
        ),
        migrations.AddField(
            model_name='usercompanyaccess',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_accesses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userroleassignment',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_role_assignments', to='organization.company'),
        ),
        migrations.AddField(
            model_name='userroleassignment',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_assignments', to='access.role'),
        ),
        migrations.AddField(
            model_name='userroleassignment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_role_assignments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userwarehouseaccess',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warehouse_accesses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userwarehouseaccess',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_accesses', to='organization.warehouse'),
        ),
        migrations.AddConstraint(
            model_name='role',
            constraint=models.UniqueConstraint(fields=('company', 'code'), name='unique_role_code_company'),
        ),
        migrations.AddConstraint(
            model_name='rolepermission',
            constraint=models.UniqueConstraint(fields=('role', 'permission'), name='unique_permission_per_role'),
        ),
        migrations.AddConstraint(
            model_name='userbranchaccess',
            constraint=models.UniqueConstraint(fields=('user', 'branch'), name='unique_user_branch_access'),
        ),
        migrations.AddConstraint(
            model_name='usercompanyaccess',
            constraint=models.UniqueConstraint(fields=('user', 'company'), name='unique_user_company_access'),
        ),
        migrations.AddConstraint(
            model_name='userroleassignment',
            constraint=models.UniqueConstraint(fields=('user', 'company', 'role'), name='unique_user_company_role'),
        ),
        migrations.AddConstraint(
            model_name='userwarehouseaccess',
            constraint=models.UniqueConstraint(fields=('user', 'warehouse'), name='unique_user_warehouse_access'),
        ),
    ]
